version: "2"
services:
  web:
     image: priteshgudge/asset-upload:v1
     ports:
     - "7500:7500"
     environment:
     - AWS_ACCESS_KEY_ID=<AWS_ACCESS_KEY>
     - AWS_SECRET_ACCESS_KEY=<AWS_ACCESS_SECRET_KEY>
     - MONGO_URI=mongodb://mongodb1:27017
     depends_on:
     - mongodb1
  mongodb1:
    image: mongo
    ports:
    - "27017:27017"
    volumes:
    - data-volume:/data/db
volumes:
  data-volume:
